//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGENDAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPS_PREVISION
    {
        public int ID_PREVISION { get; set; }
        public string NOMBRE_PREVISION { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string FECHA_EDICION { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public Nullable<int> ESTADO { get; set; }
    }
}
