//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGENDAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPS_TELEFONO
    {
        public int ID_TELEFONO { get; set; }
        public string CODIGO_TELEFONO { get; set; }
        public string NUMERO { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_EDICION { get; set; }
        public Nullable<int> PRINCIPAL { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string TIPO { get; set; }
    }
}
